package ctc

const (
	ForegroundBrightBlack                          = ForegroundBright | ForegroundBlack
	ForegroundBrightRed                            = ForegroundBright | ForegroundRed
	ForegroundBrightGreen                          = ForegroundBright | ForegroundGreen
	ForegroundBrightYellow                         = ForegroundBright | ForegroundYellow
	ForegroundBrightBlue                           = ForegroundBright | ForegroundBlue
	ForegroundBrightMagenta                        = ForegroundBright | ForegroundMagenta
	ForegroundBrightCyan                           = ForegroundBright | ForegroundCyan
	ForegroundBrightWhite                          = ForegroundBright | ForegroundWhite
	BackgroundBrightBlack                          = BackgroundBright | ForegroundBlack
	BackgroundBrightRed                            = BackgroundBright | ForegroundRed
	BackgroundBrightGreen                          = BackgroundBright | ForegroundGreen
	BackgroundBrightYellow                         = BackgroundBright | ForegroundYellow
	BackgroundBrightBlue                           = BackgroundBright | ForegroundBlue
	BackgroundBrightMagenta                        = BackgroundBright | ForegroundMagenta
	BackgroundBrightCyan                           = BackgroundBright | ForegroundCyan
	BackgroundBrightWhite                          = BackgroundBright | ForegroundWhite
	ForegroundBlackBackgroundBlack                 = ForegroundBlack | ForegroundBlack
	ForegroundRedBackgroundBlack                   = ForegroundRed | ForegroundBlack
	ForegroundGreenBackgroundBlack                 = ForegroundGreen | ForegroundBlack
	ForegroundYellowBackgroundBlack                = ForegroundYellow | ForegroundBlack
	ForegroundBlueBackgroundBlack                  = ForegroundBlue | ForegroundBlack
	ForegroundMagentaBackgroundBlack               = ForegroundMagenta | ForegroundBlack
	ForegroundCyanBackgroundBlack                  = ForegroundCyan | ForegroundBlack
	ForegroundWhiteBackgroundBlack                 = ForegroundWhite | ForegroundBlack
	ForegroundBrightBlackBackgroundBlack           = ForegroundBright | ForegroundBlack | ForegroundBlack
	ForegroundBrightRedBackgroundBlack             = ForegroundBright | ForegroundRed | ForegroundBlack
	ForegroundBrightGreenBackgroundBlack           = ForegroundBright | ForegroundGreen | ForegroundBlack
	ForegroundBrightYellowBackgroundBlack          = ForegroundBright | ForegroundYellow | ForegroundBlack
	ForegroundBrightBlueBackgroundBlack            = ForegroundBright | ForegroundBlue | ForegroundBlack
	ForegroundBrightMagentaBackgroundBlack         = ForegroundBright | ForegroundMagenta | ForegroundBlack
	ForegroundBrightCyanBackgroundBlack            = ForegroundBright | ForegroundCyan | ForegroundBlack
	ForegroundBrightWhiteBackgroundBlack           = ForegroundBright | ForegroundWhite | ForegroundBlack
	ForegroundBlackBackgroundRed                   = ForegroundBlack | ForegroundRed
	ForegroundRedBackgroundRed                     = ForegroundRed | ForegroundRed
	ForegroundGreenBackgroundRed                   = ForegroundGreen | ForegroundRed
	ForegroundYellowBackgroundRed                  = ForegroundYellow | ForegroundRed
	ForegroundBlueBackgroundRed                    = ForegroundBlue | ForegroundRed
	ForegroundMagentaBackgroundRed                 = ForegroundMagenta | ForegroundRed
	ForegroundCyanBackgroundRed                    = ForegroundCyan | ForegroundRed
	ForegroundWhiteBackgroundRed                   = ForegroundWhite | ForegroundRed
	ForegroundBrightBlackBackgroundRed             = ForegroundBright | ForegroundBlack | ForegroundRed
	ForegroundBrightRedBackgroundRed               = ForegroundBright | ForegroundRed | ForegroundRed
	ForegroundBrightGreenBackgroundRed             = ForegroundBright | ForegroundGreen | ForegroundRed
	ForegroundBrightYellowBackgroundRed            = ForegroundBright | ForegroundYellow | ForegroundRed
	ForegroundBrightBlueBackgroundRed              = ForegroundBright | ForegroundBlue | ForegroundRed
	ForegroundBrightMagentaBackgroundRed           = ForegroundBright | ForegroundMagenta | ForegroundRed
	ForegroundBrightCyanBackgroundRed              = ForegroundBright | ForegroundCyan | ForegroundRed
	ForegroundBrightWhiteBackgroundRed             = ForegroundBright | ForegroundWhite | ForegroundRed
	ForegroundBlackBackgroundGreen                 = ForegroundBlack | ForegroundGreen
	ForegroundRedBackgroundGreen                   = ForegroundRed | ForegroundGreen
	ForegroundGreenBackgroundGreen                 = ForegroundGreen | ForegroundGreen
	ForegroundYellowBackgroundGreen                = ForegroundYellow | ForegroundGreen
	ForegroundBlueBackgroundGreen                  = ForegroundBlue | ForegroundGreen
	ForegroundMagentaBackgroundGreen               = ForegroundMagenta | ForegroundGreen
	ForegroundCyanBackgroundGreen                  = ForegroundCyan | ForegroundGreen
	ForegroundWhiteBackgroundGreen                 = ForegroundWhite | ForegroundGreen
	ForegroundBrightBlackBackgroundGreen           = ForegroundBright | ForegroundBlack | ForegroundGreen
	ForegroundBrightRedBackgroundGreen             = ForegroundBright | ForegroundRed | ForegroundGreen
	ForegroundBrightGreenBackgroundGreen           = ForegroundBright | ForegroundGreen | ForegroundGreen
	ForegroundBrightYellowBackgroundGreen          = ForegroundBright | ForegroundYellow | ForegroundGreen
	ForegroundBrightBlueBackgroundGreen            = ForegroundBright | ForegroundBlue | ForegroundGreen
	ForegroundBrightMagentaBackgroundGreen         = ForegroundBright | ForegroundMagenta | ForegroundGreen
	ForegroundBrightCyanBackgroundGreen            = ForegroundBright | ForegroundCyan | ForegroundGreen
	ForegroundBrightWhiteBackgroundGreen           = ForegroundBright | ForegroundWhite | ForegroundGreen
	ForegroundBlackBackgroundYellow                = ForegroundBlack | ForegroundYellow
	ForegroundRedBackgroundYellow                  = ForegroundRed | ForegroundYellow
	ForegroundGreenBackgroundYellow                = ForegroundGreen | ForegroundYellow
	ForegroundYellowBackgroundYellow               = ForegroundYellow | ForegroundYellow
	ForegroundBlueBackgroundYellow                 = ForegroundBlue | ForegroundYellow
	ForegroundMagentaBackgroundYellow              = ForegroundMagenta | ForegroundYellow
	ForegroundCyanBackgroundYellow                 = ForegroundCyan | ForegroundYellow
	ForegroundWhiteBackgroundYellow                = ForegroundWhite | ForegroundYellow
	ForegroundBrightBlackBackgroundYellow          = ForegroundBright | ForegroundBlack | ForegroundYellow
	ForegroundBrightRedBackgroundYellow            = ForegroundBright | ForegroundRed | ForegroundYellow
	ForegroundBrightGreenBackgroundYellow          = ForegroundBright | ForegroundGreen | ForegroundYellow
	ForegroundBrightYellowBackgroundYellow         = ForegroundBright | ForegroundYellow | ForegroundYellow
	ForegroundBrightBlueBackgroundYellow           = ForegroundBright | ForegroundBlue | ForegroundYellow
	ForegroundBrightMagentaBackgroundYellow        = ForegroundBright | ForegroundMagenta | ForegroundYellow
	ForegroundBrightCyanBackgroundYellow           = ForegroundBright | ForegroundCyan | ForegroundYellow
	ForegroundBrightWhiteBackgroundYellow          = ForegroundBright | ForegroundWhite | ForegroundYellow
	ForegroundBlackBackgroundBlue                  = ForegroundBlack | ForegroundBlue
	ForegroundRedBackgroundBlue                    = ForegroundRed | ForegroundBlue
	ForegroundGreenBackgroundBlue                  = ForegroundGreen | ForegroundBlue
	ForegroundYellowBackgroundBlue                 = ForegroundYellow | ForegroundBlue
	ForegroundBlueBackgroundBlue                   = ForegroundBlue | ForegroundBlue
	ForegroundMagentaBackgroundBlue                = ForegroundMagenta | ForegroundBlue
	ForegroundCyanBackgroundBlue                   = ForegroundCyan | ForegroundBlue
	ForegroundWhiteBackgroundBlue                  = ForegroundWhite | ForegroundBlue
	ForegroundBrightBlackBackgroundBlue            = ForegroundBright | ForegroundBlack | ForegroundBlue
	ForegroundBrightRedBackgroundBlue              = ForegroundBright | ForegroundRed | ForegroundBlue
	ForegroundBrightGreenBackgroundBlue            = ForegroundBright | ForegroundGreen | ForegroundBlue
	ForegroundBrightYellowBackgroundBlue           = ForegroundBright | ForegroundYellow | ForegroundBlue
	ForegroundBrightBlueBackgroundBlue             = ForegroundBright | ForegroundBlue | ForegroundBlue
	ForegroundBrightMagentaBackgroundBlue          = ForegroundBright | ForegroundMagenta | ForegroundBlue
	ForegroundBrightCyanBackgroundBlue             = ForegroundBright | ForegroundCyan | ForegroundBlue
	ForegroundBrightWhiteBackgroundBlue            = ForegroundBright | ForegroundWhite | ForegroundBlue
	ForegroundBlackBackgroundMagenta               = ForegroundBlack | ForegroundMagenta
	ForegroundRedBackgroundMagenta                 = ForegroundRed | ForegroundMagenta
	ForegroundGreenBackgroundMagenta               = ForegroundGreen | ForegroundMagenta
	ForegroundYellowBackgroundMagenta              = ForegroundYellow | ForegroundMagenta
	ForegroundBlueBackgroundMagenta                = ForegroundBlue | ForegroundMagenta
	ForegroundMagentaBackgroundMagenta             = ForegroundMagenta | ForegroundMagenta
	ForegroundCyanBackgroundMagenta                = ForegroundCyan | ForegroundMagenta
	ForegroundWhiteBackgroundMagenta               = ForegroundWhite | ForegroundMagenta
	ForegroundBrightBlackBackgroundMagenta         = ForegroundBright | ForegroundBlack | ForegroundMagenta
	ForegroundBrightRedBackgroundMagenta           = ForegroundBright | ForegroundRed | ForegroundMagenta
	ForegroundBrightGreenBackgroundMagenta         = ForegroundBright | ForegroundGreen | ForegroundMagenta
	ForegroundBrightYellowBackgroundMagenta        = ForegroundBright | ForegroundYellow | ForegroundMagenta
	ForegroundBrightBlueBackgroundMagenta          = ForegroundBright | ForegroundBlue | ForegroundMagenta
	ForegroundBrightMagentaBackgroundMagenta       = ForegroundBright | ForegroundMagenta | ForegroundMagenta
	ForegroundBrightCyanBackgroundMagenta          = ForegroundBright | ForegroundCyan | ForegroundMagenta
	ForegroundBrightWhiteBackgroundMagenta         = ForegroundBright | ForegroundWhite | ForegroundMagenta
	ForegroundBlackBackgroundCyan                  = ForegroundBlack | ForegroundCyan
	ForegroundRedBackgroundCyan                    = ForegroundRed | ForegroundCyan
	ForegroundGreenBackgroundCyan                  = ForegroundGreen | ForegroundCyan
	ForegroundYellowBackgroundCyan                 = ForegroundYellow | ForegroundCyan
	ForegroundBlueBackgroundCyan                   = ForegroundBlue | ForegroundCyan
	ForegroundMagentaBackgroundCyan                = ForegroundMagenta | ForegroundCyan
	ForegroundCyanBackgroundCyan                   = ForegroundCyan | ForegroundCyan
	ForegroundWhiteBackgroundCyan                  = ForegroundWhite | ForegroundCyan
	ForegroundBrightBlackBackgroundCyan            = ForegroundBright | ForegroundBlack | ForegroundCyan
	ForegroundBrightRedBackgroundCyan              = ForegroundBright | ForegroundRed | ForegroundCyan
	ForegroundBrightGreenBackgroundCyan            = ForegroundBright | ForegroundGreen | ForegroundCyan
	ForegroundBrightYellowBackgroundCyan           = ForegroundBright | ForegroundYellow | ForegroundCyan
	ForegroundBrightBlueBackgroundCyan             = ForegroundBright | ForegroundBlue | ForegroundCyan
	ForegroundBrightMagentaBackgroundCyan          = ForegroundBright | ForegroundMagenta | ForegroundCyan
	ForegroundBrightCyanBackgroundCyan             = ForegroundBright | ForegroundCyan | ForegroundCyan
	ForegroundBrightWhiteBackgroundCyan            = ForegroundBright | ForegroundWhite | ForegroundCyan
	ForegroundBlackBackgroundWhite                 = ForegroundBlack | ForegroundWhite
	ForegroundRedBackgroundWhite                   = ForegroundRed | ForegroundWhite
	ForegroundGreenBackgroundWhite                 = ForegroundGreen | ForegroundWhite
	ForegroundYellowBackgroundWhite                = ForegroundYellow | ForegroundWhite
	ForegroundBlueBackgroundWhite                  = ForegroundBlue | ForegroundWhite
	ForegroundMagentaBackgroundWhite               = ForegroundMagenta | ForegroundWhite
	ForegroundCyanBackgroundWhite                  = ForegroundCyan | ForegroundWhite
	ForegroundWhiteBackgroundWhite                 = ForegroundWhite | ForegroundWhite
	ForegroundBrightBlackBackgroundWhite           = ForegroundBright | ForegroundBlack | ForegroundWhite
	ForegroundBrightRedBackgroundWhite             = ForegroundBright | ForegroundRed | ForegroundWhite
	ForegroundBrightGreenBackgroundWhite           = ForegroundBright | ForegroundGreen | ForegroundWhite
	ForegroundBrightYellowBackgroundWhite          = ForegroundBright | ForegroundYellow | ForegroundWhite
	ForegroundBrightBlueBackgroundWhite            = ForegroundBright | ForegroundBlue | ForegroundWhite
	ForegroundBrightMagentaBackgroundWhite         = ForegroundBright | ForegroundMagenta | ForegroundWhite
	ForegroundBrightCyanBackgroundWhite            = ForegroundBright | ForegroundCyan | ForegroundWhite
	ForegroundBrightWhiteBackgroundWhite           = ForegroundBright | ForegroundWhite | ForegroundWhite
	ForegroundBlackBackgroundBrightBlack           = ForegroundBlack | BackgroundBright | ForegroundBlack
	ForegroundRedBackgroundBrightBlack             = ForegroundRed | BackgroundBright | ForegroundBlack
	ForegroundGreenBackgroundBrightBlack           = ForegroundGreen | BackgroundBright | ForegroundBlack
	ForegroundYellowBackgroundBrightBlack          = ForegroundYellow | BackgroundBright | ForegroundBlack
	ForegroundBlueBackgroundBrightBlack            = ForegroundBlue | BackgroundBright | ForegroundBlack
	ForegroundMagentaBackgroundBrightBlack         = ForegroundMagenta | BackgroundBright | ForegroundBlack
	ForegroundCyanBackgroundBrightBlack            = ForegroundCyan | BackgroundBright | ForegroundBlack
	ForegroundWhiteBackgroundBrightBlack           = ForegroundWhite | BackgroundBright | ForegroundBlack
	ForegroundBrightBlackBackgroundBrightBlack     = ForegroundBright | ForegroundBlack | BackgroundBright | ForegroundBlack
	ForegroundBrightRedBackgroundBrightBlack       = ForegroundBright | ForegroundRed | BackgroundBright | ForegroundBlack
	ForegroundBrightGreenBackgroundBrightBlack     = ForegroundBright | ForegroundGreen | BackgroundBright | ForegroundBlack
	ForegroundBrightYellowBackgroundBrightBlack    = ForegroundBright | ForegroundYellow | BackgroundBright | ForegroundBlack
	ForegroundBrightBlueBackgroundBrightBlack      = ForegroundBright | ForegroundBlue | BackgroundBright | ForegroundBlack
	ForegroundBrightMagentaBackgroundBrightBlack   = ForegroundBright | ForegroundMagenta | BackgroundBright | ForegroundBlack
	ForegroundBrightCyanBackgroundBrightBlack      = ForegroundBright | ForegroundCyan | BackgroundBright | ForegroundBlack
	ForegroundBrightWhiteBackgroundBrightBlack     = ForegroundBright | ForegroundWhite | BackgroundBright | ForegroundBlack
	ForegroundBlackBackgroundBrightRed             = ForegroundBlack | BackgroundBright | ForegroundRed
	ForegroundRedBackgroundBrightRed               = ForegroundRed | BackgroundBright | ForegroundRed
	ForegroundGreenBackgroundBrightRed             = ForegroundGreen | BackgroundBright | ForegroundRed
	ForegroundYellowBackgroundBrightRed            = ForegroundYellow | BackgroundBright | ForegroundRed
	ForegroundBlueBackgroundBrightRed              = ForegroundBlue | BackgroundBright | ForegroundRed
	ForegroundMagentaBackgroundBrightRed           = ForegroundMagenta | BackgroundBright | ForegroundRed
	ForegroundCyanBackgroundBrightRed              = ForegroundCyan | BackgroundBright | ForegroundRed
	ForegroundWhiteBackgroundBrightRed             = ForegroundWhite | BackgroundBright | ForegroundRed
	ForegroundBrightBlackBackgroundBrightRed       = ForegroundBright | ForegroundBlack | BackgroundBright | ForegroundRed
	ForegroundBrightRedBackgroundBrightRed         = ForegroundBright | ForegroundRed | BackgroundBright | ForegroundRed
	ForegroundBrightGreenBackgroundBrightRed       = ForegroundBright | ForegroundGreen | BackgroundBright | ForegroundRed
	ForegroundBrightYellowBackgroundBrightRed      = ForegroundBright | ForegroundYellow | BackgroundBright | ForegroundRed
	ForegroundBrightBlueBackgroundBrightRed        = ForegroundBright | ForegroundBlue | BackgroundBright | ForegroundRed
	ForegroundBrightMagentaBackgroundBrightRed     = ForegroundBright | ForegroundMagenta | BackgroundBright | ForegroundRed
	ForegroundBrightCyanBackgroundBrightRed        = ForegroundBright | ForegroundCyan | BackgroundBright | ForegroundRed
	ForegroundBrightWhiteBackgroundBrightRed       = ForegroundBright | ForegroundWhite | BackgroundBright | ForegroundRed
	ForegroundBlackBackgroundBrightGreen           = ForegroundBlack | BackgroundBright | ForegroundGreen
	ForegroundRedBackgroundBrightGreen             = ForegroundRed | BackgroundBright | ForegroundGreen
	ForegroundGreenBackgroundBrightGreen           = ForegroundGreen | BackgroundBright | ForegroundGreen
	ForegroundYellowBackgroundBrightGreen          = ForegroundYellow | BackgroundBright | ForegroundGreen
	ForegroundBlueBackgroundBrightGreen            = ForegroundBlue | BackgroundBright | ForegroundGreen
	ForegroundMagentaBackgroundBrightGreen         = ForegroundMagenta | BackgroundBright | ForegroundGreen
	ForegroundCyanBackgroundBrightGreen            = ForegroundCyan | BackgroundBright | ForegroundGreen
	ForegroundWhiteBackgroundBrightGreen           = ForegroundWhite | BackgroundBright | ForegroundGreen
	ForegroundBrightBlackBackgroundBrightGreen     = ForegroundBright | ForegroundBlack | BackgroundBright | ForegroundGreen
	ForegroundBrightRedBackgroundBrightGreen       = ForegroundBright | ForegroundRed | BackgroundBright | ForegroundGreen
	ForegroundBrightGreenBackgroundBrightGreen     = ForegroundBright | ForegroundGreen | BackgroundBright | ForegroundGreen
	ForegroundBrightYellowBackgroundBrightGreen    = ForegroundBright | ForegroundYellow | BackgroundBright | ForegroundGreen
	ForegroundBrightBlueBackgroundBrightGreen      = ForegroundBright | ForegroundBlue | BackgroundBright | ForegroundGreen
	ForegroundBrightMagentaBackgroundBrightGreen   = ForegroundBright | ForegroundMagenta | BackgroundBright | ForegroundGreen
	ForegroundBrightCyanBackgroundBrightGreen      = ForegroundBright | ForegroundCyan | BackgroundBright | ForegroundGreen
	ForegroundBrightWhiteBackgroundBrightGreen     = ForegroundBright | ForegroundWhite | BackgroundBright | ForegroundGreen
	ForegroundBlackBackgroundBrightYellow          = ForegroundBlack | BackgroundBright | ForegroundYellow
	ForegroundRedBackgroundBrightYellow            = ForegroundRed | BackgroundBright | ForegroundYellow
	ForegroundGreenBackgroundBrightYellow          = ForegroundGreen | BackgroundBright | ForegroundYellow
	ForegroundYellowBackgroundBrightYellow         = ForegroundYellow | BackgroundBright | ForegroundYellow
	ForegroundBlueBackgroundBrightYellow           = ForegroundBlue | BackgroundBright | ForegroundYellow
	ForegroundMagentaBackgroundBrightYellow        = ForegroundMagenta | BackgroundBright | ForegroundYellow
	ForegroundCyanBackgroundBrightYellow           = ForegroundCyan | BackgroundBright | ForegroundYellow
	ForegroundWhiteBackgroundBrightYellow          = ForegroundWhite | BackgroundBright | ForegroundYellow
	ForegroundBrightBlackBackgroundBrightYellow    = ForegroundBright | ForegroundBlack | BackgroundBright | ForegroundYellow
	ForegroundBrightRedBackgroundBrightYellow      = ForegroundBright | ForegroundRed | BackgroundBright | ForegroundYellow
	ForegroundBrightGreenBackgroundBrightYellow    = ForegroundBright | ForegroundGreen | BackgroundBright | ForegroundYellow
	ForegroundBrightYellowBackgroundBrightYellow   = ForegroundBright | ForegroundYellow | BackgroundBright | ForegroundYellow
	ForegroundBrightBlueBackgroundBrightYellow     = ForegroundBright | ForegroundBlue | BackgroundBright | ForegroundYellow
	ForegroundBrightMagentaBackgroundBrightYellow  = ForegroundBright | ForegroundMagenta | BackgroundBright | ForegroundYellow
	ForegroundBrightCyanBackgroundBrightYellow     = ForegroundBright | ForegroundCyan | BackgroundBright | ForegroundYellow
	ForegroundBrightWhiteBackgroundBrightYellow    = ForegroundBright | ForegroundWhite | BackgroundBright | ForegroundYellow
	ForegroundBlackBackgroundBrightBlue            = ForegroundBlack | BackgroundBright | ForegroundBlue
	ForegroundRedBackgroundBrightBlue              = ForegroundRed | BackgroundBright | ForegroundBlue
	ForegroundGreenBackgroundBrightBlue            = ForegroundGreen | BackgroundBright | ForegroundBlue
	ForegroundYellowBackgroundBrightBlue           = ForegroundYellow | BackgroundBright | ForegroundBlue
	ForegroundBlueBackgroundBrightBlue             = ForegroundBlue | BackgroundBright | ForegroundBlue
	ForegroundMagentaBackgroundBrightBlue          = ForegroundMagenta | BackgroundBright | ForegroundBlue
	ForegroundCyanBackgroundBrightBlue             = ForegroundCyan | BackgroundBright | ForegroundBlue
	ForegroundWhiteBackgroundBrightBlue            = ForegroundWhite | BackgroundBright | ForegroundBlue
	ForegroundBrightBlackBackgroundBrightBlue      = ForegroundBright | ForegroundBlack | BackgroundBright | ForegroundBlue
	ForegroundBrightRedBackgroundBrightBlue        = ForegroundBright | ForegroundRed | BackgroundBright | ForegroundBlue
	ForegroundBrightGreenBackgroundBrightBlue      = ForegroundBright | ForegroundGreen | BackgroundBright | ForegroundBlue
	ForegroundBrightYellowBackgroundBrightBlue     = ForegroundBright | ForegroundYellow | BackgroundBright | ForegroundBlue
	ForegroundBrightBlueBackgroundBrightBlue       = ForegroundBright | ForegroundBlue | BackgroundBright | ForegroundBlue
	ForegroundBrightMagentaBackgroundBrightBlue    = ForegroundBright | ForegroundMagenta | BackgroundBright | ForegroundBlue
	ForegroundBrightCyanBackgroundBrightBlue       = ForegroundBright | ForegroundCyan | BackgroundBright | ForegroundBlue
	ForegroundBrightWhiteBackgroundBrightBlue      = ForegroundBright | ForegroundWhite | BackgroundBright | ForegroundBlue
	ForegroundBlackBackgroundBrightMagenta         = ForegroundBlack | BackgroundBright | ForegroundMagenta
	ForegroundRedBackgroundBrightMagenta           = ForegroundRed | BackgroundBright | ForegroundMagenta
	ForegroundGreenBackgroundBrightMagenta         = ForegroundGreen | BackgroundBright | ForegroundMagenta
	ForegroundYellowBackgroundBrightMagenta        = ForegroundYellow | BackgroundBright | ForegroundMagenta
	ForegroundBlueBackgroundBrightMagenta          = ForegroundBlue | BackgroundBright | ForegroundMagenta
	ForegroundMagentaBackgroundBrightMagenta       = ForegroundMagenta | BackgroundBright | ForegroundMagenta
	ForegroundCyanBackgroundBrightMagenta          = ForegroundCyan | BackgroundBright | ForegroundMagenta
	ForegroundWhiteBackgroundBrightMagenta         = ForegroundWhite | BackgroundBright | ForegroundMagenta
	ForegroundBrightBlackBackgroundBrightMagenta   = ForegroundBright | ForegroundBlack | BackgroundBright | ForegroundMagenta
	ForegroundBrightRedBackgroundBrightMagenta     = ForegroundBright | ForegroundRed | BackgroundBright | ForegroundMagenta
	ForegroundBrightGreenBackgroundBrightMagenta   = ForegroundBright | ForegroundGreen | BackgroundBright | ForegroundMagenta
	ForegroundBrightYellowBackgroundBrightMagenta  = ForegroundBright | ForegroundYellow | BackgroundBright | ForegroundMagenta
	ForegroundBrightBlueBackgroundBrightMagenta    = ForegroundBright | ForegroundBlue | BackgroundBright | ForegroundMagenta
	ForegroundBrightMagentaBackgroundBrightMagenta = ForegroundBright | ForegroundMagenta | BackgroundBright | ForegroundMagenta
	ForegroundBrightCyanBackgroundBrightMagenta    = ForegroundBright | ForegroundCyan | BackgroundBright | ForegroundMagenta
	ForegroundBrightWhiteBackgroundBrightMagenta   = ForegroundBright | ForegroundWhite | BackgroundBright | ForegroundMagenta
	ForegroundBlackBackgroundBrightCyan            = ForegroundBlack | BackgroundBright | ForegroundCyan
	ForegroundRedBackgroundBrightCyan              = ForegroundRed | BackgroundBright | ForegroundCyan
	ForegroundGreenBackgroundBrightCyan            = ForegroundGreen | BackgroundBright | ForegroundCyan
	ForegroundYellowBackgroundBrightCyan           = ForegroundYellow | BackgroundBright | ForegroundCyan
	ForegroundBlueBackgroundBrightCyan             = ForegroundBlue | BackgroundBright | ForegroundCyan
	ForegroundMagentaBackgroundBrightCyan          = ForegroundMagenta | BackgroundBright | ForegroundCyan
	ForegroundCyanBackgroundBrightCyan             = ForegroundCyan | BackgroundBright | ForegroundCyan
	ForegroundWhiteBackgroundBrightCyan            = ForegroundWhite | BackgroundBright | ForegroundCyan
	ForegroundBrightBlackBackgroundBrightCyan      = ForegroundBright | ForegroundBlack | BackgroundBright | ForegroundCyan
	ForegroundBrightRedBackgroundBrightCyan        = ForegroundBright | ForegroundRed | BackgroundBright | ForegroundCyan
	ForegroundBrightGreenBackgroundBrightCyan      = ForegroundBright | ForegroundGreen | BackgroundBright | ForegroundCyan
	ForegroundBrightYellowBackgroundBrightCyan     = ForegroundBright | ForegroundYellow | BackgroundBright | ForegroundCyan
	ForegroundBrightBlueBackgroundBrightCyan       = ForegroundBright | ForegroundBlue | BackgroundBright | ForegroundCyan
	ForegroundBrightMagentaBackgroundBrightCyan    = ForegroundBright | ForegroundMagenta | BackgroundBright | ForegroundCyan
	ForegroundBrightCyanBackgroundBrightCyan       = ForegroundBright | ForegroundCyan | BackgroundBright | ForegroundCyan
	ForegroundBrightWhiteBackgroundBrightCyan      = ForegroundBright | ForegroundWhite | BackgroundBright | ForegroundCyan
	ForegroundBlackBackgroundBrightWhite           = ForegroundBlack | BackgroundBright | ForegroundWhite
	ForegroundRedBackgroundBrightWhite             = ForegroundRed | BackgroundBright | ForegroundWhite
	ForegroundGreenBackgroundBrightWhite           = ForegroundGreen | BackgroundBright | ForegroundWhite
	ForegroundYellowBackgroundBrightWhite          = ForegroundYellow | BackgroundBright | ForegroundWhite
	ForegroundBlueBackgroundBrightWhite            = ForegroundBlue | BackgroundBright | ForegroundWhite
	ForegroundMagentaBackgroundBrightWhite         = ForegroundMagenta | BackgroundBright | ForegroundWhite
	ForegroundCyanBackgroundBrightWhite            = ForegroundCyan | BackgroundBright | ForegroundWhite
	ForegroundWhiteBackgroundBrightWhite           = ForegroundWhite | BackgroundBright | ForegroundWhite
	ForegroundBrightBlackBackgroundBrightWhite     = ForegroundBright | ForegroundBlack | BackgroundBright | ForegroundWhite
	ForegroundBrightRedBackgroundBrightWhite       = ForegroundBright | ForegroundRed | BackgroundBright | ForegroundWhite
	ForegroundBrightGreenBackgroundBrightWhite     = ForegroundBright | ForegroundGreen | BackgroundBright | ForegroundWhite
	ForegroundBrightYellowBackgroundBrightWhite    = ForegroundBright | ForegroundYellow | BackgroundBright | ForegroundWhite
	ForegroundBrightBlueBackgroundBrightWhite      = ForegroundBright | ForegroundBlue | BackgroundBright | ForegroundWhite
	ForegroundBrightMagentaBackgroundBrightWhite   = ForegroundBright | ForegroundMagenta | BackgroundBright | ForegroundWhite
	ForegroundBrightCyanBackgroundBrightWhite      = ForegroundBright | ForegroundCyan | BackgroundBright | ForegroundWhite
	ForegroundBrightWhiteBackgroundBrightWhite     = ForegroundBright | ForegroundWhite | BackgroundBright | ForegroundWhite
)
